local ADDON, addon = ...

addon.GamePadButtonList = {
   "FACER",
   "FACEU",
   "FACED",
   "FACEL",
   "DPADR",
   "DPADU",
   "DPADD",
   "DPADL",
   "STCKL",
   "STCKR",
   "SPADL",
   "SPADR",
   "TRIGL",
   "TRIGR",
   "PPADL",
   "PPADR"
}

addon.GamePadModifierList = {
   "SPADL",
   "SPADR",
   "PPADL",
   "PPADR"
}

CrossHotbar_DB = {
   ActivePreset = 3,
   Presets = {
      [1] = {
         Mutable = false,
         Name = "Gamepad_Preset",
         SwapType = "NONE",
         WXHBType = "HIDE",
         DDAAType = "DADA",
         PadActions = {
            FACER = {BIND="PAD2",         ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN5"},
            FACEU = {BIND="PAD4",         ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN6"},
            FACED = {BIND="PAD1",         ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN7"},
            FACEL = {BIND="PAD3" ,        ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN8"},
            DPADR = {BIND="PADDRIGHT",    ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN9"},
            DPADU = {BIND="PADDUP",       ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN10"},
            DPADD = {BIND="PADDDOWN",     ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN11"},
            DPADL = {BIND="PADDLEFT",     ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN12"},
            STCKL = {BIND="PADLSTICK",    ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
            STCKR = {BIND="PADRSTICK",    ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
            SPADL = {BIND="PADLSHOULDER", ACTION="CAMERAPAGE1",      TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="RIGHTSHOULDER",    SWAPTRIGACTION="TARGETNEARESTENEMY"},
            SPADR = {BIND="PADRSHOULDER", ACTION="RIGHTSHOULDER",    TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="CAMERAPAGE1",      SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
            TRIGL = {BIND="PADLTRIGGER",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            TRIGR = {BIND="PADRTRIGGER",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADL = {BIND="PADPADDLE1",   ACTION="LEFTPADDLE",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADR = {BIND="PADPADDLE2",   ACTION="RIGHTPADDLE",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}
         }
      },
      [2] = {
         Mutable = false,
         Name = "Keyboard_Preset",
         SwapType = "NONE",
         WXHBType = "HIDE",
         DDAAType = "DADA",
         PadActions = {
            FACER = {BIND="1",  ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN5"},
            FACEU = {BIND="2",  ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN6"},
            FACED = {BIND="3",  ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN7"},
            FACEL = {BIND="4" , ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN8"},
            DPADR = {BIND="5",  ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN9"},
            DPADU = {BIND="6",  ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN10"},
            DPADD = {BIND="7",  ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN11"},
            DPADL = {BIND="8",  ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN12"},
            STCKL = {BIND="9",  ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
            STCKR = {BIND="0",  ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
            SPADL = {BIND="-",  ACTION="CAMERAPAGE1",      TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="RIGHTSHOULDER",    SWAPTRIGACTION="TARGETNEARESTENEMY"},
            SPADR = {BIND="=",  ACTION="RIGHTSHOULDER",    TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="CAMERAPAGE1",      SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
            TRIGL = {BIND="[",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            TRIGR = {BIND="]",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADL = {BIND="\\", ACTION="LEFTPADDLE",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADR = {BIND="'",  ACTION="RIGHTPADDLE",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}                
         }
      },
      [3] = {
         Mutable = false,
         Name = "SC_Preset",
         SwapType = "LEFTPADDLE",
         WXHBType = "SHOW",
         DDAAType = "DDAA",
         PadActions = {
            FACER = {BIND="1",  ACTION="NONE",             TRIGACTION="HOTBARBTN1",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="HOTBARBTN5",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            FACEU = {BIND="2",  ACTION="NONE",             TRIGACTION="HOTBARBTN2",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="HOTBARBTN6",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            FACED = {BIND="3",  ACTION="NONE",             TRIGACTION="HOTBARBTN3",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="HOTBARBTN7",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            FACEL = {BIND="4" , ACTION="NONE",             TRIGACTION="HOTBARBTN4",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="HOTBARBTN8",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADR = {BIND="5",  ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN9",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVRIGHT",     PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADU = {BIND="6",  ACTION="JUMP",             TRIGACTION="HOTBARBTN10",         SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVUP",        PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADD = {BIND="7",  ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN11",         SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVDOWN",      PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADL = {BIND="8",  ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN12",         SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVLEFT",      PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            STCKL = {BIND="9",  ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            STCKR = {BIND="0",  ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            SPADL = {BIND="-",  ACTION="LEFTSHOULDER",     TRIGACTION="TARGETPREVIOUSENEMY", SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            SPADR = {BIND="=",  ACTION="RIGHTSHOULDER",    TRIGACTION="TARGETNEARESTENEMY",  SPADLACTION="SHEATH",        SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            TRIGL = {BIND="[",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            TRIGR = {BIND="]",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            PPADL = {BIND="\\", ACTION="LEFTPADDLE",       TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            PPADR = {BIND="'",  ACTION="RIGHTPADDLE",      TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",             PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"}
         }
      },
      [4] = {
         Mutable = true,
         Name = "Custom",
         SwapType = "LEFTPADDLE",
         WXHBType = "SHOW",
         DDAAType = "DDAA",
         PadActions = {
            FACER = {BIND="PAD2",         ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="PAGEONE",      SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVRIGHT",            PPADLTRIGACTION="HOTBARBTN5",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            FACEU = {BIND="PAD4",         ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="PAGETWO",      SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVUP",               PPADLTRIGACTION="HOTBARBTN6",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            FACED = {BIND="PAD1",         ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="PAGETHREE",    SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVDOWN",             PPADLTRIGACTION="HOTBARBTN7",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            FACEL = {BIND="PAD3" ,        ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="PAGEFOUR",     SPADRTRIGACTION="NONE",     PPADLACTION="UNITNAVLEFT",             PPADLTRIGACTION="HOTBARBTN8",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADR = {BIND="PADDRIGHT",    ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NEXTPAGE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="HOTBARBTN9",      PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADU = {BIND="PADDUP",       ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="ZOOMIN",       SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="HOTBARBTN10",     PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADD = {BIND="PADDDOWN",     ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="ZOOMOUT",      SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="HOTBARBTN11",     PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            DPADL = {BIND="PADDLEFT",     ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="PREVPAGE",     SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="HOTBARBTN12",     PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            STCKL = {BIND="PADLSTICK",    ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            STCKR = {BIND="PADRSTICK",    ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            SPADL = {BIND="PADLSHOULDER", ACTION="LEFTSHOULDER",     TRIGACTION="TARGETPREVIOUSENEMY", SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="TARGETLASTHOSTILE",       PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            SPADR = {BIND="PADRSHOULDER", ACTION="RIGHTSHOULDER",    TRIGACTION="TARGETNEARESTENEMY",  SPADLACTION="SHEATH",        SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="ASSISTTARGET",            PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            TRIGL = {BIND="PADLTRIGGER",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            TRIGR = {BIND="PADRTRIGGER",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            PPADL = {BIND="PADPADDLE2",   ACTION="LEFTPADDLE",       TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"},
            PPADR = {BIND="PADPADDLE3",   ACTION="RIGHTPADDLE",      TRIGACTION="NONE",                SPADLACTION="NONE",          SPADLTRIGACTION="NONE",     SPADRACTION="NONE",         SPADRTRIGACTION="NONE",     PPADLACTION="NONE",                    PPADLTRIGACTION="NONE",            PPADRACTION="NONE",      PPADRTRIGACTION="NONE"}
         }
      }
   }
}

addon.Config = {
   Mutable = true,
   Name = "Custom",
   SwapType = "LEFTSHOULDER",
   WXHBType = "HIDE",
   DDAAType = "DDAA",
   PadActions = {
      FACER = {BIND="PAD2",         ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN5"},
      FACEU = {BIND="PAD4",         ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN6"},
      FACED = {BIND="PAD1",         ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN7"},
      FACEL = {BIND="PAD3" ,        ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN8"},
      DPADR = {BIND="PADDRIGHT",    ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      DPADU = {BIND="PADDUP",       ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      DPADD = {BIND="PADDDOWN",     ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      DPADL = {BIND="PADDLEFT",     ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      STCKL = {BIND="PADLSTICK",    ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
      STCKR = {BIND="PADRSTICK",    ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
      SPADL = {BIND="PADLSHOULDER", ACTION="LEFTSHOULDER",     TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="RIGHTSHOULDER",    SWAPTRIGACTION="TARGETNEARESTENEMY"},
      SPADR = {BIND="PADRSHOULDER", ACTION="RIGHTSHOULDER",    TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="LEFTSHOULDER",     SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
      TRIGL = {BIND="PADLTRIGGER",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      TRIGR = {BIND="PADRTRIGGER",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      PPADL = {BIND="PADPADDLE2",   ACTION="LEFTPADDLE",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      PPADR = {BIND="PADPADDLE4",   ACTION="RIGHTPADDLE",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}
   }
}

function addon.Config:ConfigListAdd(listname, valuetable, initvalue)
   if addon[listname] == nil then
      addon[listname] = {initvalue}
   end
   
   local keys = {}
   for key in pairs(valuetable) do
      table.insert(keys, key)
   end
   table.sort(keys)

   for i,key in ipairs(keys) do
      table.insert(addon[listname], key)
   end
end

function addon.Config:StorePreset(to, from)
   if to.Mutable then
      if from.Mutable then
         to.Name = from.Name
      end
      to.SwapType = from.SwapType
      to.WXHBType = from.WXHBType
      to.DDAAType = from.DDAAType
      for button, attributes in pairs(from.PadActions) do
         for key, value in pairs(attributes) do
            to.PadActions[button][key] = value 
         end
      end
   end
end

function addon.Config:ProcessConfig(config)
end

local config = addon.Config
local preset = CrossHotbar_DB.ActivePreset;
config:StorePreset(config, CrossHotbar_DB.Presets[preset])
