local ADDON, addon = ...

CrossHotbar_DB = {
   ActivePreset = 3,
   Presets = {
      [1] = {
         Mutable = false,
         Name = "Gamepad_Preset",
         SwapType = 2,
         WXHBType = 2,
         PadActions = {
            FACER = {BIND="PAD2",         ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN5"},
            FACEU = {BIND="PAD4",         ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN6"},
            FACED = {BIND="PAD1",         ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN7"},
            FACEL = {BIND="PAD3" ,        ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN8"},
            DPADR = {BIND="PADDRIGHT",    ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN9"},
            DPADU = {BIND="PADDUP",       ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN10"},
            DPADD = {BIND="PADDDOWN",     ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN11"},
            DPADL = {BIND="PADDLEFT",     ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN12"},
            STCKL = {BIND="PADLSTICK",    ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
            STCKR = {BIND="PADRSTICK",    ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
            SPADL = {BIND="PADLSHOULDER", ACTION="CAMERAPAGE1",      TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="CAMERAPAGE2",      SWAPTRIGACTION="TARGETNEARESTENEMY"},
            SPADR = {BIND="PADRSHOULDER", ACTION="CAMERAPAGE2",      TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="CAMERAPAGE1",      SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
            TRIGL = {BIND="PADLTRIGGER",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            TRIGR = {BIND="PADRTRIGGER",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADL = {BIND="PADPADDLE1",   ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADR = {BIND="PADPADDLE2",   ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}
         }
      },
      [2] = {
         Mutable = false,
         Name = "Keyboard_Preset",
         SwapType = 4,
         WXHBType = 2,
         PadActions = {
            FACER = {BIND="1",  ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN5"},
            FACEU = {BIND="2",  ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN6"},
            FACED = {BIND="3",  ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN7"},
            FACEL = {BIND="4" , ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN8"},
            DPADR = {BIND="5",  ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN9"},
            DPADU = {BIND="6",  ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN10"},
            DPADD = {BIND="7",  ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN11"},
            DPADL = {BIND="8",  ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN12"},
            STCKL = {BIND="9",  ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
            STCKR = {BIND="0",  ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
            SPADL = {BIND="-",  ACTION="CAMERAPAGE1",      TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="CAMERAPAGE2",      SWAPTRIGACTION="TARGETNEARESTENEMY"},
            SPADR = {BIND="=",  ACTION="CAMERAPAGE2",      TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="CAMERAPAGE1",      SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
            TRIGL = {BIND="[",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            TRIGR = {BIND="]",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADL = {BIND="\\", ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADR = {BIND="'",  ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}
         }
      },
      [3] = {
         Mutable = false,
         Name = "SC_Preset",
         SwapType = 4,
         WXHBType = 2,
         PadActions = {
            FACER = {BIND="1",  ACTION="NONE",             TRIGACTION="HOTBARBTN1",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN5"},
            FACEU = {BIND="2",  ACTION="NONE",             TRIGACTION="HOTBARBTN2",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN6"},
            FACED = {BIND="3",  ACTION="NONE",             TRIGACTION="HOTBARBTN3",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN7"},
            FACEL = {BIND="4" , ACTION="NONE",             TRIGACTION="HOTBARBTN4",          SWAPACTION="NONE",             SWAPTRIGACTION="HOTBARBTN8"},
            DPADR = {BIND="5",  ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN9",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN9"},
            DPADU = {BIND="6",  ACTION="JUMP",             TRIGACTION="HOTBARBTN10",         SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN10"},
            DPADD = {BIND="7",  ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN11",         SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN11"},
            DPADL = {BIND="8",  ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN12",         SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN12"},
            STCKL = {BIND="9",  ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
            STCKR = {BIND="0",  ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
            SPADL = {BIND="-",  ACTION="CAMERAPAGE1",      TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="CAMERAPAGE2",      SWAPTRIGACTION="TARGETNEARESTENEMY"},
            SPADR = {BIND="=",  ACTION="CAMERAPAGE2",      TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="CAMERAPAGE1",      SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
            TRIGL = {BIND="[",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            TRIGR = {BIND="]",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADL = {BIND="\\", ACTION="SWAPHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADR = {BIND="'",  ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}
         }
      },
      [4] = {
         Mutable = true,
         Name = "Custom",
         SwapType = 2,
         WXHBType = 2,
         PadActions = {
            FACER = {BIND="PAD2",         ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN5"},
            FACEU = {BIND="PAD4",         ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN6"},
            FACED = {BIND="PAD1",         ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN7"},
            FACEL = {BIND="PAD3" ,        ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN8"},
            DPADR = {BIND="PADDRIGHT",    ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            DPADU = {BIND="PADDUP",       ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            DPADD = {BIND="PADDDOWN",     ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            DPADL = {BIND="PADDLEFT",     ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            STCKL = {BIND="PADLSTICK",    ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
            STCKR = {BIND="PADRSTICK",    ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
            SPADL = {BIND="PADLSHOULDER", ACTION="SWAPHOTBAR",       TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="CAMERAPAGE2",      SWAPTRIGACTION="TARGETNEARESTENEMY"},
            SPADR = {BIND="PADRSHOULDER", ACTION="CAMERAPAGE2",      TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="CAMERAPAGE1",      SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
            TRIGL = {BIND="PADLTRIGGER",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            TRIGR = {BIND="PADRTRIGGER",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADL = {BIND="PADPADDLE1",   ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
            PPADR = {BIND="PADPADDLE2",   ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}
         }
      }
   }
}

addon.Config = {
   Mutable = true,
   Name = "Custom",
   SwapType = 2,
   WXHBType = 2,
   PadActions = {
      FACER = {BIND="PAD2",         ACTION="CLEARTARGETING",   TRIGACTION="HOTBARBTN1",          SWAPACTION="UNITNAVRIGHT",     SWAPTRIGACTION="HOTBARBTN5"},
      FACEU = {BIND="PAD4",         ACTION="JUMP",             TRIGACTION="HOTBARBTN2",          SWAPACTION="UNITNAVUP",        SWAPTRIGACTION="HOTBARBTN6"},
      FACED = {BIND="PAD1",         ACTION="INTERACTTARGET",   TRIGACTION="HOTBARBTN3",          SWAPACTION="UNITNAVDOWN",      SWAPTRIGACTION="HOTBARBTN7"},
      FACEL = {BIND="PAD3" ,        ACTION="TOGGLEWORLDMAP",   TRIGACTION="HOTBARBTN4",          SWAPACTION="UNITNAVLEFT",      SWAPTRIGACTION="HOTBARBTN8"},
      DPADR = {BIND="PADDRIGHT",    ACTION="UNITNAVRIGHT",     TRIGACTION="HOTBARBTN5",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      DPADU = {BIND="PADDUP",       ACTION="UNITNAVUP",        TRIGACTION="HOTBARBTN6",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      DPADD = {BIND="PADDDOWN",     ACTION="UNITNAVDOWN",      TRIGACTION="HOTBARBTN7",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      DPADL = {BIND="PADDLEFT",     ACTION="UNITNAVLEFT",      TRIGACTION="HOTBARBTN8",          SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      STCKL = {BIND="PADLSTICK",    ACTION="MACRO CH_MACRO_1", TRIGACTION="NONE",                SWAPACTION="MACRO CH_MACRO_1", SWAPTRIGACTION="MACRO CH_MACRO_1"},
      STCKR = {BIND="PADRSTICK",    ACTION="TOGGLESHEATH",     TRIGACTION="EXTRAACTIONBUTTON1",  SWAPACTION="TOGGLESHEATH",     SWAPTRIGACTION="EXTRAACTIONBUTTON1"},
      SPADL = {BIND="PADLSHOULDER", ACTION="CAMERAPAGE1",      TRIGACTION="TARGETPREVIOUSENEMY", SWAPACTION="CAMERAPAGE2",      SWAPTRIGACTION="TARGETNEARESTENEMY"},
      SPADR = {BIND="PADRSHOULDER", ACTION="CAMERAPAGE2",      TRIGACTION="TARGETNEARESTENEMY",  SWAPACTION="CAMERAPAGE1",      SWAPTRIGACTION="TARGETPREVIOUSENEMY"},
      TRIGL = {BIND="PADLTRIGGER",  ACTION="LEFTHOTBAR",       TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      TRIGR = {BIND="PADRTRIGGER",  ACTION="RIGHTHOTBAR",      TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      PPADL = {BIND="PADPADDLE1",   ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"},
      PPADR = {BIND="PADPADDLE2",   ACTION="NONE",             TRIGACTION="NONE",                SWAPACTION="NONE",             SWAPTRIGACTION="NONE"}
   }
}

function addon.Config:StorePreset(to, from)
   if to.Mutable then
      if from.Mutable then
         to.Name = from.Name
      end
      to.SwapType = from.SwapType
      to.WXHBType = from.WXHBType
      for button, attributes in pairs(from.PadActions) do
         for key, value in pairs(attributes) do
            to.PadActions[button][key] = value 
         end
      end
   end
end

function addon.Config:ProcessConfig(config)
end

local config = addon.Config
local preset = CrossHotbar_DB.ActivePreset;
config:StorePreset(config, CrossHotbar_DB.Presets[preset])
